//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAdoptionServicesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetActivity
    {
        public PetActivity()
        {
            this.Pets = new HashSet<Pet>();
        }
    
        public int Id { get; set; }
        public string Activity { get; set; }
    
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
