//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAdoptionServicesAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetAdoptionDBEntities : DbContext
    {
        public PetAdoptionDBEntities()
            : base("name=PetAdoptionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<PetActivity> PetActivities { get; set; }
        public virtual DbSet<PetImageGallery> PetImageGalleries { get; set; }
        public virtual DbSet<PetPublisher> PetPublishers { get; set; }
        public virtual DbSet<PetSize> PetSizes { get; set; }
        public virtual DbSet<PetType> PetTypes { get; set; }
    }
}
